jitterbunk_project/jitterbunk/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # /jitterbunk/
    url(r'^$', views.index, name='index'),
    # /jitterbunk/all/
    url(r'^all/?$', views.UserListView.as_view(), name='user-list'),
    # /jitterbunk/bunk/
    url(r'^bunk/', views.send_bunk, name='send_bunk'),
    # /jitterbunk/user/[username]
    url(r'^user/(?P<username>.*)$', views.view_individual_bunks, name='view_individual_bunks'),
]

jitterbunk_project/jitterbunk_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^jitterbunk/', include('jitterbunk.urls', namespace='jitterbunk')),
    url(r'^admin/', include(admin.site.urls)),
]

jitterbunk_project/jitterbunk/models.py
'''
File: jitterbunk/models.py
Author: Neel Kishnani

This file defines the database models for the
jitterbug project. Here we define a Bunk and a
UserProfile. A Bunk is the poking mechanism
and the UserProfile is an abstraction above the
default Django User.
'''

from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    '''
    A single UserProfile object. Here we map the user
    one to one with the default Django user. We specify
    the photo as a string (URL of the photo).
    '''
    user  = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.CharField(max_length=200)


class Bunk(models.Model):
    '''
    A single Bunk object. Here we define the metadata
    for the object, denoting who the Bunk is coming from,
    who it's going to, and what time it was sent.
    '''
    from_user = models.ForeignKey(User, related_name='bunks_sent')
    to_user   = models.ForeignKey(User, related_name='bunks_received')
    time      = models.DateTimeField('date published')

jitterbunk_project/jitterbunk/views.py
'''
File: jitterbunk/views.py
Author: Neel Kishnani

This file defines the different views of the jitterbunk
application. Here we're able to pull up a feed of all
jitterbunks, send a bunk from one user to another, and
pull up the jitterbunk feed for a specific user.
'''

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import UserProfile, Bunk
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Q
from django.views.generic import ListView

class UserListView(ListView):
    '''
    This view serves mostly as a test of the
    ListView functionality. We list all users
    in the db.
    '''
    model = User
    template_name = 'jitterbunk/user_list.html'

def index(request):
    '''
    Landing page for jitterbunk. Here we
    display a full history of bunks.
    '''
    bunks = Bunk.objects.all()
    context = {'bunks': bunks}
    return render(request, 'jitterbunk/index.html', context)


def send_bunk(request):
    '''
    Here we will have a form through which
    people can specify who to send a bunk to/
    from.
    '''
    if request.POST:
        try:
            from_username = request.POST['from_user']
            to_username   = request.POST['to_user']

            from_user = User.objects.get(username=from_username)
            to_user   = User.objects.get(username=to_username)

            bunk = Bunk(from_user=from_user, to_user=to_user, time=timezone.now())
            bunk.save()
            return HttpResponseRedirect('/jitterbunk/')

        except (KeyError, User.DoesNotExist):
            return render(request, 'jitterbunk/send_bunk.html', {
                'error_message':"Username not found."
            })

    return render(request, 'jitterbunk/send_bunk.html')


def view_individual_bunks(request, username):
    '''
    Given a specific username, we display the bunks sent
    to or sent from that user.
    '''
    u  = User.objects.get(username=username)
    individual_bunks = Bunk.objects.filter(Q(from_user=u) | Q(to_user=u))
    context = {'individual_bunks':individual_bunks, 'username':username}
    return render(request, 'jitterbunk/individual.html', context)

jitterbunk_project/jitterbunk/templates/jitterbunk/index.html
<h3>Bunks</h3>

{% if bunks %}
<ul>
    {% for bunk in bunks %}
    <li>
        {{bunk.from_user.username}} sent a bunk to {{bunk.to_user.username}} at {{bunk.time}}
    </li>
    {% endfor %}
</ul>

{% else %}
<p>Waiting for bunks...</p>
{% endif %}

jitterbunk_project/jitterbunk/templates/jitterbunk/individual.html
<h3>Bunks for {{username}}</h3>

{% if individual_bunks %}
<ul>
    {% for bunk in individual_bunks %}
    <li>
        {{bunk.from_user.username}} sent a bunk to {{bunk.to_user.username}} at {{bunk.time}}
    </li>
    {% endfor %}
</ul>

{% else %}
<p>Waiting for bunks...</p>
{% endif %}

jitterbunk_project/jitterbunk/templates/jitterbunk/send_bunk.html
<!DOCTYPE html>
<html>
<body>

<h2>Send a Bunk</h2>

<form action = "{% url 'jitterbunk:send_bunk' %}" method="post">
{% csrf_token %}
  <label for="from_user">From:</label><br>
  <input type="text" id="from_user" name="from_user"><br>
  <label for="to_user">To:</label><br>
  <input type="text" id="to_user" name="to_user"><br><br>
  <input type="submit" value="Submit">
</form>

<p>If you click the "Submit" button, the form data will be uploaded to /jitterbunk/</p>

</body>
</html>

jitterbunk_project/jitterbunk/templates/jitterbunk/user_list.html
<ul>
    {% for user in object_list %}
    <li>
        {{user.username}}
    </li>
    {% endfor %}
</ul>